apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-001-jk
spec:
  capacity:
   storage: 5Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: sc-jk
  mountOptions:
   - hard
   - nfsvers=4.1
  nfs:
   path: /t12022/branch02
   server: 10.240.0.252
