apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: win 
  namespace: default 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: win
  template: 
    metadata: 
      labels: 
        app: win
    containers:
      - name: windowswebserver
        image: mcr.microsoft.com/windows/servercore:ltsc2019
        command:
        - powershell.exe
        name: win
        volumeMounts: 
        - mountPath: \\10.0.0.4\PrintT12022
          name: hostpath-example 
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always 
      volumes: 
      - name: hostpath-example 
        hostPath: 
          path: \\10.0.0.4\PrintT12022
