apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: htestpod 
  namespace: default 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: test-pod
  template: 
    metadata: 
      labels: 
        app: Test=Pod
    spec: 
      containers: 
      - image: mcr.microsoft.com/windows/nanoserver:1809
        name: wincontainer
        volumeMounts: 
        - mountPath: \\10.0.0.4\PrintT12022
          name: hostpath-example 
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always 
      volumes: 
      - name: hostpath-example 
        hostPath: 
          path: \\10.0.0.4\PrintT12022
